wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.17
    cli_version: 0.17.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1718094243
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 23
      4: 3.9.17
      5: 0.17.1
      8:
      - 3
      - 5
      13: windows-amd64
ro:
  desc: null
  value: 25.0
num_steps:
  desc: null
  value: 500
n_epochs:
  desc: null
  value: 100
batch_size:
  desc: null
  value: 1024
initial_lr:
  desc: null
  value: 0.0005
lr_schedule:
  desc: null
  value:
    '75': 0.001
    '100': 0.0001
