wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.17
    cli_version: 0.17.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1718094558
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 23
      4: 3.9.17
      5: 0.17.1
      8:
      - 3
      - 5
      13: windows-amd64
